# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=250)),
                ('cliente_calle', models.CharField(max_length=250)),
                ('cliente_numext', models.IntegerField()),
                ('cliente_numint', models.CharField(max_length=250)),
                ('cliente_colonia', models.CharField(max_length=250)),
                ('cliente_del_mun', models.CharField(max_length=250)),
                ('cliente_cp', models.IntegerField()),
                ('cliente_telefono', models.BigIntegerField()),
                ('cliente_rfc', models.CharField(max_length=14)),
                ('cliente_umodificacion', models.DateTimeField(auto_now=True)),
                ('cliente_status', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja')], default='activo', max_length=10)),
                ('cliente_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comisionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionista_nombre', models.CharField(max_length=250)),
                ('comisionista_cuenta', models.IntegerField()),
                ('comisionista_rfc', models.CharField(max_length=250)),
                ('comisionista_telefono', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_efectivo', models.IntegerField()),
                ('costo_total', models.IntegerField()),
                ('costo_comisionista', models.IntegerField()),
                ('costo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costo_cliente', to='operacion.Cliente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_mombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento_fecha', models.DateField(auto_now_add=True)),
                ('movimiento_umodificacion', models.DateTimeField(auto_now=True)),
                ('movimiento_factura', models.CharField(max_length=20)),
                ('movimiento_banco', models.CharField(max_length=25)),
                ('movimiento_regreso_total', models.IntegerField()),
                ('movimiento_referencia', models.IntegerField()),
                ('movimiento_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_cliente', to='operacion.Cliente')),
                ('movimiento_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_empresa', to='operacion.Empresa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoComisionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovimientoComisionista_comisionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisionistamovimiento', to='operacion.Comisionista')),
                ('MovimientoComisionista_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movientocomisionista', to='operacion.Movimiento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Regreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regreso_monto', models.IntegerField()),
                ('regreso_tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia')], default='cheque', max_length=15)),
                ('regreso_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regresos_movimiento', to='operacion.Movimiento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
